# Generated by Django 5.0.6 on 2024-06-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_attributes',
        ),
    ]
